# Generated by Django 6.0.6 on 2026-06-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('santa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='santa_assignments', to='api.naughtyornicelist')),
                ('santee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='santee_assignments', to='api.naughtyornicelist')),
            ],
        ),
    ]
